/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetTAL;

import java.util.ArrayList;
import javax.swing.JCheckBox;
import java.awt.Color;

/**
 *
 * @author Manence
 */
public class JPanelReponses extends javax.swing.JPanel {

    private ArrayList<Reponse> reponses;
            
    private ArrayList<JCheckBox> boxes;
    /**
     * Creates new form JPanelReponses
     */
    public JPanelReponses()
    {
        initComponents();
    };
    
    public JPanelReponses(int nbReponses) {
        boxes = new ArrayList<JCheckBox>();
        for (int i = 0; i < nbReponses; i++)
        {
            JCheckBox n = new JCheckBox();
            this.boxes.add(n);
            this.add(n);
        }
        initComponents();
    }

    public void setReponses(ArrayList<Reponse> liste)
    {
        this.reponses = liste;
        for (int i = 0; i < this.boxes.size(); i++)
        {
            this.boxes.get(i).setSelected(false);
            this.boxes.get(i).setForeground(Color.BLACK);
            this.boxes.get(i).setText(liste.get(i).getTexte());
        }
    }
    
    public ArrayList<Boolean> getAnswer()
    {
        ArrayList<Boolean> answer = new ArrayList<Boolean>();
        for (JCheckBox box : this.boxes)
            answer.add(box.isSelected());
        return answer;
    }
    
    public void showSolutions()
    {
        for (int i = 0; i < this.boxes.size(); i++)
        {
//            if (this.reponses.get(i).getValue() == this.boxes.get(i).isSelected())
            if (this.reponses.get(i).getValue())
                this.boxes.get(i).setForeground(Color.GREEN);
            else
                this.boxes.get(i).setForeground(Color.RED);

        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(this.boxes.size(), 2));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
