/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetTAL;

import java.io.File;
import java.io.FileNotFoundException;

import edu.stanford.nlp.io.IOUtils;
import edu.stanford.nlp.pipeline.StanfordCoreNLP;

/**
 *
 * @author Manence
 */
public class JPanelNew extends javax.swing.JPanel {
    
    private QCM qcm;
    private JFrameQCM jFrameQCM;
    private StanfordCoreNLP pipeline;
    
    /**
     * Creates new form NewJPanel
     */
    public JPanelNew() {
        jFrameQCM = null;
        this.pipeline = new StanfordCoreNLP();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldFichier = new javax.swing.JTextField();
        jButtonFichier = new javax.swing.JButton();
        jLabelNbQuestions = new javax.swing.JLabel();
        jLabelNbChoix = new javax.swing.JLabel();
        jTextFieldNbQuestions = new javax.swing.JTextField();
        jTextFieldNbChoix = new javax.swing.JTextField();
        jButtonOk = new javax.swing.JButton();

        jTextFieldFichier.setText("./in.txt");

        jButtonFichier.setText("Fichier");
        jButtonFichier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFichierActionPerformed(evt);
            }
        });

        jLabelNbQuestions.setText("Nombre de questions: ");

        jLabelNbChoix.setText("Nombre de choix: ");

        jTextFieldNbQuestions.setText("10");

        jTextFieldNbChoix.setText("5");

        jButtonOk.setText("Creer QCM");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jButtonOkActionPerformed(evt);
				} catch (NumberFormatException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (FileNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNbChoix)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNbChoix))
                            .addComponent(jLabelNbQuestions))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNbQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 240, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextFieldFichier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonOk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonFichier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFichier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFichier))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNbQuestions)
                    .addComponent(jTextFieldNbQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNbChoix)
                    .addComponent(jTextFieldNbChoix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addComponent(jButtonOk)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFichierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFichierActionPerformed
    javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
    if (fileChooser.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION){
  File file = fileChooser.getSelectedFile();
  this.jTextFieldFichier.setText(file.getPath());
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFichierActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) throws NumberFormatException, FileNotFoundException {//GEN-FIRST:event_jButtonOkActionPerformed
        String titre = this.jTextFieldFichier.getText();
    	String texte = new String(IOUtils.slurpFileNoExceptions(titre));
        this.qcm = new QCM(texte, titre, Integer.parseInt(this.jTextFieldNbQuestions.getText()), Integer.parseInt(this.jTextFieldNbChoix.getText()), this.pipeline);
    	System.out.println(this.qcm.getTitre());

        System.out.print(this.qcm.toText());
        if (jFrameQCM != null)
            jFrameQCM.dispose();
        jFrameQCM = new JFrameQCM(this.qcm);
        jFrameQCM.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButtonOkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFichier;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabelNbChoix;
    private javax.swing.JLabel jLabelNbQuestions;
    private javax.swing.JTextField jTextFieldFichier;
    private javax.swing.JTextField jTextFieldNbChoix;
    private javax.swing.JTextField jTextFieldNbQuestions;
    // End of variables declaration//GEN-END:variables
}
